name: g_notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_hooks: ^0.20.4
  riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  go_router: ^13.0.1
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
